---
- name: "Apache installation using Docker on CentOS 7"
  hosts: prod
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
    #vars_files:
    #     - /home/vagrant/webapp/files/.secrets/credentials.vault
  pre_tasks:
  - name: Install Python 3 and pip3
    package:
        name: "{{ item }}"
        state: present
    loop:
          - python3
          - python3-pip
          - git 
          - wget
    when: ansible_distribution == "Ubuntu"

  - name: Install Docker module for Python
    pip:
        name: docker
        executable: pip3
  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/vagrant/index.html
    - name: Create Apache container using Docker
      community.docker.docker_container:
        name: webapp
        image: httpd
        recreate: true
        state: started 
        ports:
          - "80:80"
        volumes:
             - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html

